export const DEFAULT_PROJECTS = [
  {
    id: "1",
    title: "Dashboard Fintech",
    subtitle: "Design Produit • Développement",
    category: "Fintech",
    isFeatured: true,
    showOnProjects: true,
    mediaType: "image",
    mediaUrl: "",
    colorClass: "bg-gray-800",
    icon: "fas fa-chart-line",
  },
  {
    id: "2",
    title: "App Santé",
    subtitle: "App Mobile • Stratégie UX",
    category: "Santé",
    isFeatured: true,
    showOnProjects: true,
    mediaType: "image",
    mediaUrl: "",
    colorClass: "bg-indigo-100",
    icon: "",
  },
  {
    id: "3",
    title: "Refonte E-Commerce",
    subtitle: "Branding • Shopify",
    category: "E-commerce",
    isFeatured: true,
    showOnProjects: true,
    mediaType: "image",
    mediaUrl: "",
    colorClass: "bg-pink-50",
    icon: "fas fa-mobile-alt",
  },
  {
    id: "4",
    title: "Architecture SaaS",
    subtitle: "Backend • Infrastructure",
    category: "SaaS",
    isFeatured: true,
    showOnProjects: true,
    mediaType: "image",
    mediaUrl: "",
    colorClass: "bg-diez-dark",
    icon: "fas fa-layer-group",
  },
];

export const normalizeProjects = (projects) =>
  projects.map((project) => ({
    showOnProjects: project.showOnProjects !== false,
    isFeatured: Boolean(project.isFeatured),
    mediaUrl: project.mediaUrl || "",
    mediaType: project.mediaType || "image",
    ...project,
  }));
