'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'fr' | 'en';

interface LangContextType {
  lang: Lang;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    'nav-home': 'Accueil',
    'nav-services': 'Expertise',
    'nav-process': 'Process',
    'nav-portfolio': 'Réalisations',
    'nav-testimonials': 'Avis',
    'nav-contact': 'Contact',
    'hero-badge': 'Agence Mieux Notée 2025',
    'hero-cta1': 'Auditer mon Business',
    'hero-cta2': 'Nos Réalisations',
    'hero-float-1-title': 'Croissance +120%',
    'hero-float-1-desc': 'Rapport Analytics',
    'hero-float-2-title': 'Utilisateurs Actifs',
    'hero-subtitle': 'Nous créons les outils sur-mesure qui automatisent votre activité.',
    'hero-subtitle-strong': 'Délais garantis. Budget respecté. Zéro jargon technique.',
    'partners-title': 'Ils nous font confiance',
    'work-title': 'Projets Sélectionnés',
    'work-subtitle': "Nous ne faisons pas que du design; nous construisons des écosystèmes digitaux qui scalent.",
    'work-link': 'Voir tous les projets',
    'bento-label': 'Notre Expertise',
    'bento-title': "Tout ce qu'il faut pour Automatiser",
    'bento-subtitle': "De l'analyse de vos processus jusqu'au déploiement final, nous couvrons tous les aspects techniques et créatifs.",
    'bento-1-title': 'Interfaces & Ergonomie',
    'bento-1-desc': "Nous concevons des outils internes intuitifs que vos équipes prendront plaisir à utiliser au quotidien. Fini les logiciels complexes.",
    'bento-2-title': 'Développement Sur-Mesure',
    'bento-2-desc': 'Des systèmes robustes pour digitaliser votre métier.',
    'bento-3-title': 'Automatisation',
    'bento-3-desc': 'Connexions API & CRM.',
    'bento-4-title': 'Accessibilité',
    'bento-4-desc': 'Vos outils sur mobile & tablette.',
    'steps-label': 'Notre Processus',
    'steps-title': "De l'Audit à l'Action",
    'step-1-title': 'Audit & Compréhension',
    'step-1-desc': "Nous commençons par comprendre votre métier. Nous analysons vos goulots d'étranglement et vos pertes de temps pour définir où l'automatisation aura le plus d'impact ROI.",
    'step-2-title': 'Construction Agile',
    'step-2-desc': "Pas d'effet tunnel. Nous développons vos outils étape par étape. Vous validez chaque fonctionnalité toutes les deux semaines. Vous gardez le contrôle total sur le budget et la direction.",
    'step-3-title': 'Déploiement & Formation',
    'step-3-desc': "La technique n'est rien sans adoption. Nous installons les outils et formons vos équipes pour qu'elles gagnent du temps dès le premier jour. Zéro rupture d'activité.",
    'testim-title': 'Ils nous font confiance',
    'testim-subtitle': "Des résultats concrets, pas de promesses en l'air.",
    'testim-1': '"On perdait 2 jours par semaine sur Excel. Diez a créé un outil sur-mesure qui a tout automatisé. L\'investissement a été rentabilisé en 3 mois."',
    'testim-2': '"J\'avais peur que ce soit trop technique pour nous. L\'équipe a été ultra-pédagogue et l\'outil est hyper simple à utiliser. Je recommande."',
    'testim-3': '"Enfin une agence qui respecte les délais ! Outil livré à la date prévue, budget respecté à l\'euro près. Ça change tout."',
    'pricing-title': 'Prix Simples, Grande Valeur',
    'pricing-subtitle': "Choisissez le plan adapté à votre stade. Pas de frais cachés, juste des résultats.",
    'price-1-title': 'Démarrage',
    'price-1-period': '/mois',
    'price-1-desc': 'Parfait pour les MVPs et la validation rapide.',
    'price-1-f1': 'Système de Design',
    'price-1-f2': '5 Pages Frontend',
    'price-1-f3': 'SEO de base',
    'price-1-f4': 'Support Backend',
    'price-1-btn': 'Commencer',
    'price-2-badge': 'Populaire',
    'price-2-title': 'Croissance',
    'price-2-period': '/mois',
    'price-2-desc': 'Pour les équipes en croissance nécessitant un partenaire produit.',
    'price-2-f1': 'Suite UI/UX Complète',
    'price-2-f2': 'App React/Next.js',
    'price-2-f3': 'Intégration API',
    'price-2-f4': 'Sprints Hebdomadaires',
    'price-2-btn': 'Choisir Pro',
    'price-3-title': 'Entreprise',
    'price-3-period': '/devis',
    'price-3-desc': 'Transformation digitale complète pour organisations établies.',
    'price-3-f1': 'Équipe Dédiée (5+)',
    'price-3-f2': 'Support 24/7',
    'price-3-f3': 'Architecture Cloud',
    'price-3-f4': 'Sécurité Avancée',
    'price-3-btn': 'Contacter Ventes',
    'faq-title': 'Questions Fréquentes',
    'faq-q1': 'Combien de temps dure un projet typique ?',
    'faq-a1': 'Les délais varient selon la complexité. Une landing page peut prendre 2 semaines, un SaaS complet 8-12 semaines. Nous travaillons en sprints de 2 semaines pour montrer des progrès constants.',
    'faq-q2': 'Assurez-vous le support après lancement ?',
    'faq-a2': 'Absolument. Nous proposons plusieurs forfaits de maintenance pour garder votre produit sécurisé et à jour.',
    'faq-q3': 'Quelles technologies utilisez-vous ?',
    'faq-a3': 'Nous sommes experts de la stack Javascript moderne : React, Next.js, Node.js et Tailwind CSS pour le frontend et le backend.',
    'manifesto-label': 'Notre Philosophie',
    'manifesto-text': "Nous croyons que la technologie doit servir votre métier, pas le complexifier. Un mauvais logiciel tue la croissance. Un bon outil libère le potentiel de vos équipes. Nous ne vendons pas des lignes de code, nous vendons de la sérénité et de la performance.",
    'cta-title-1': 'Prêt à passer à la',
    'cta-title-2': 'vitesse supérieure ?',
    'cta-subtitle': "Rejoignez les dirigeants qui ont choisi l'efficacité. Transformons vos processus manuels en avantages compétitifs.",
    'cta-btn-1': "Lancer l'Audit Gratuit",
    'cta-btn-2': 'Voir les Cas Clients',
    'footer-desc': 'Nous construisons des produits digitaux qui définissent des catégories et stimulent la croissance.',
    'footer-h-services': 'Services',
    'footer-l-web': 'Développement Web',
    'footer-l-mob': 'Apps Mobiles',
    'footer-l-ui': 'Design UI/UX',
    'footer-l-consult': 'Consulting',
    'footer-h-company': 'Agence',
    'footer-l-about': 'À Propos',
    'footer-l-careers': 'Carrières',
    'footer-l-blog': 'Blog',
    'footer-l-contact': 'Contact',
    'footer-h-newsletter': 'Newsletter',
    'footer-news-text': 'Recevez les dernières tendances.',
    'footer-email-ph': 'Votre email',
    'contact-id': 'contact',
  },
  en: {
    'nav-home': 'Home',
    'nav-services': 'Expertise',
    'nav-process': 'Process',
    'nav-portfolio': 'Portfolio',
    'nav-testimonials': 'Reviews',
    'nav-contact': 'Contact',
    'hero-badge': 'Top Rated Agency 2025',
    'hero-cta1': 'Audit My Business',
    'hero-cta2': 'Our Work',
    'hero-float-1-title': 'Growth +120%',
    'hero-float-1-desc': 'Analytics Report',
    'hero-float-2-title': 'Active Users',
    'hero-subtitle': 'We build custom tools that automate your business.',
    'hero-subtitle-strong': 'Guaranteed deadlines. Respected budget. No technical jargon.',
    'partners-title': 'Trusted by Innovative Companies',
    'work-title': 'Selected Work',
    'work-subtitle': "We don't just design; we build digital ecosystems that scale.",
    'work-link': 'View all projects',
    'bento-label': 'Our Expertise',
    'bento-title': 'Everything you need to Automate',
    'bento-subtitle': 'From process analysis to final deployment, we cover all technical and creative aspects.',
    'bento-1-title': 'Interfaces & Ergonomics',
    'bento-1-desc': 'We design intuitive internal tools that your teams will enjoy using every day. No more complex software.',
    'bento-2-title': 'Custom Development',
    'bento-2-desc': 'Robust systems to digitize your business.',
    'bento-3-title': 'Automation',
    'bento-3-desc': 'API & CRM Connections.',
    'bento-4-title': 'Accessibility',
    'bento-4-desc': 'Your tools on mobile & tablet.',
    'steps-label': 'Our Process',
    'steps-title': 'From Audit to Action',
    'step-1-title': 'Audit & Understanding',
    'step-1-desc': 'We start by understanding your business. We analyze your bottlenecks and time losses to define where automation will have the most ROI impact.',
    'step-2-title': 'Agile Construction',
    'step-2-desc': 'No tunnel effect. We develop your tools step by step. You validate each feature every two weeks. You keep full control over budget and direction.',
    'step-3-title': 'Deployment & Training',
    'step-3-desc': 'Technology is nothing without adoption. We install the tools and train your teams so they save time from day one. Zero business disruption.',
    'testim-title': 'They Trust Us',
    'testim-subtitle': 'Concrete results, no empty promises.',
    'testim-1': '"We were losing 2 days a week on Excel. Diez created a custom tool that automated everything. The investment paid off in 3 months."',
    'testim-2': '"I was afraid it would be too technical for us. The team was super educational and the tool is super simple to use. I recommend."',
    'testim-3': '"Finally an agency that respects deadlines! Tool delivered on the scheduled date, budget respected to the euro. It changes everything."',
    'pricing-title': 'Simple Pricing, Big Value',
    'pricing-subtitle': 'Choose the plan that fits your stage. No hidden fees, just results.',
    'price-1-title': 'Starter',
    'price-1-period': '/mo',
    'price-1-desc': 'Perfect for MVPs and small startups needing quick validation.',
    'price-1-f1': 'Design System',
    'price-1-f2': '5 Pages Frontend',
    'price-1-f3': 'Basic SEO',
    'price-1-f4': 'Backend Support',
    'price-1-btn': 'Get Started',
    'price-2-badge': 'Most Popular',
    'price-2-title': 'Scale Up',
    'price-2-period': '/mo',
    'price-2-desc': 'For growing teams that need a dedicated product partner.',
    'price-2-f1': 'Full UI/UX Suite',
    'price-2-f2': 'React/Next.js App',
    'price-2-f3': 'API Integration',
    'price-2-f4': 'Weekly Sprints',
    'price-2-btn': 'Choose Professional',
    'price-3-title': 'Enterprise',
    'price-3-period': '/quote',
    'price-3-desc': 'Full digital transformation for established organizations.',
    'price-3-f1': 'Dedicated Team (5+)',
    'price-3-f2': '24/7 Support',
    'price-3-f3': 'Cloud Architecture',
    'price-3-f4': 'Advanced Security',
    'price-3-btn': 'Contact Sales',
    'faq-title': 'Frequently Asked Questions',
    'faq-q1': 'How long does a typical project take?',
    'faq-a1': 'Timelines vary depending on complexity. A simple landing page might take 2 weeks, while a full SaaS MVP usually takes 8-12 weeks. We work in 2-week sprints to show consistent progress.',
    'faq-q2': 'Do you provide post-launch support?',
    'faq-a2': 'Absolutely. We offer various maintenance packages to ensure your product stays secure, updated, and bug-free after launch.',
    'faq-q3': 'What technologies do you use?',
    'faq-a3': 'We specialize in the modern Javascript stack: React, Next.js, Node.js, and Tailwind CSS on the frontend/backend. For mobile, we use React Native.',
    'manifesto-label': 'Our Philosophy',
    'manifesto-text': "We believe technology should serve your business, not complicate it. Bad software kills growth. A good tool unleashes your team's potential. We don't sell lines of code, we sell serenity and performance.",
    'cta-title-1': 'Ready to shift to the',
    'cta-title-2': 'next gear?',
    'cta-subtitle': "Join the leaders who chose efficiency. Let's transform your manual processes into competitive advantages.",
    'cta-btn-1': 'Launch Free Audit',
    'cta-btn-2': 'See Case Studies',
    'footer-desc': 'We build digital products that define categories and drive business growth.',
    'footer-h-services': 'Services',
    'footer-l-web': 'Web Development',
    'footer-l-mob': 'Mobile Apps',
    'footer-l-ui': 'UI/UX Design',
    'footer-l-consult': 'Consulting',
    'footer-h-company': 'Company',
    'footer-l-about': 'About Us',
    'footer-l-careers': 'Careers',
    'footer-l-blog': 'Blog',
    'footer-l-contact': 'Contact',
    'footer-h-newsletter': 'Newsletter',
    'footer-news-text': 'Get the latest trends in your inbox.',
    'footer-email-ph': 'Enter email',
    'contact-id': 'contact',
  },
};

const LangContext = createContext<LangContextType>({
  lang: 'fr',
  toggleLanguage: () => {},
  t: (key: string) => key,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('fr');

  const toggleLanguage = () => setLang((l) => (l === 'fr' ? 'en' : 'fr'));
  const t = (key: string) => translations[lang][key] ?? key;

  return (
    <LangContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
