'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useRouter, usePathname } from 'next/navigation';

export type Lang = 'fr' | 'en';

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    'nav-home': 'Accueil',
    'nav-services': 'Services',
    'nav-process': 'Process',
    'nav-portfolio': 'Réalisations',
    'nav-blog': 'Blog',
    'nav-testimonials': 'Avis',
    'nav-contact': 'Contact',

    // ── Services ──
    'services-label': 'Ce que nous faisons',
    'services-title': 'Nos Services',
    'services-title-accent': 'Sur‑Mesure',
    'services-subtitle': "Chaque service est pensé pour générer un impact mesurable sur votre croissance.",
    'services-cta': 'Démarrer un projet',
    'services-link': 'Voir tous les services',
    'services-discover': 'Découvrir ce service',
    'services-back': '← Retour',
    'services-included': 'Ce qui est inclus',
    'services-results': 'Résultats typiques',
    'services-faq': 'Questions fréquentes',
    'services-cta-page-title': 'Prêt à démarrer ?',
    'services-cta-page-sub': 'Audit gratuit · Réponse en 24h · Devis transparent',
    'services-cta-page-btn': "Demander un devis gratuit",

    // Service 1 — SaaS / Web / App
    'srv1-title': 'SaaS, Sites Web & Applications',
    'srv1-tagline': 'Votre idée en produit digital complet',
    'srv1-short': 'Design, développement et déploiement de plateformes web, SaaS et applications sur‑mesure.',
    'srv1-desc': "De la maquette au déploiement, nous concevons des produits digitaux robustes et scalables. Interfaces modernes, backend solide, expérience utilisateur soignée — livrés dans les délais.",
    'srv1-f1': 'Design UI/UX & prototype Figma',
    'srv1-f2': 'Développement Next.js / React',
    'srv1-f3': 'Backend & API sur‑mesure',
    'srv1-f4': 'Base de données & authentification',
    'srv1-f5': 'Déploiement cloud & CI/CD',
    'srv1-f6': 'SEO technique & performance',
    'srv1-r1': '-60% de temps de développement vs agence classique',
    'srv1-r2': 'Livraison MVP en 4–8 semaines',
    'srv1-r3': 'Score Lighthouse > 90 garanti',
    'srv1-faq-q1': 'Quelle est la durée moyenne pour un SaaS ?',
    'srv1-faq-a1': 'Un MVP fonctionnel est livrable en 6–8 semaines. Nous travaillons en sprints de 2 semaines avec validation continue.',
    'srv1-faq-q2': 'Proposez-vous la maintenance après livraison ?',
    'srv1-faq-a2': 'Oui, avec des forfaits maintenance mensuels incluant mises à jour, monitoring et corrections.',

    // Service 2 — LLC
    'srv2-title': 'Création de LLC Complète',
    'srv2-tagline': 'Lancez votre entreprise aux États‑Unis en 72h',
    'srv2-short': 'Création clé en main de votre LLC américaine : immatriculation, EIN, compte bancaire et conformité.',
    'srv2-desc': "Nous gérons l'intégralité du processus d'incorporation aux États‑Unis. LLC enregistrée, EIN obtenu, adresse registered agent, compte bancaire pro ouvert — sans que vous n'ayez à vous déplacer.",
    'srv2-f1': 'Enregistrement LLC dans l\'État optimal (Wyoming, Delaware…)',
    'srv2-f2': 'Obtention de l\'EIN (numéro fiscal US)',
    'srv2-f3': 'Registered Agent 12 mois inclus',
    'srv2-f4': 'Ouverture de compte bancaire US en ligne',
    'srv2-f5': 'Operating Agreement rédigé',
    'srv2-f6': 'Conformité annuelle & rappels',
    'srv2-r1': 'LLC opérationnelle en moins de 72h',
    'srv2-r2': '100% en ligne, sans déplacement',
    'srv2-r3': 'Accès aux paiements Stripe / PayPal US',
    'srv2-faq-q1': 'Dois‑je être résident américain ?',
    'srv2-faq-a1': 'Non. Toute personne physique de nationalité étrangère peut créer une LLC aux États‑Unis sans visa ni résidence.',
    'srv2-faq-q2': 'Quels États recommandez‑vous ?',
    'srv2-faq-a2': 'Wyoming pour la confidentialité et les frais réduits, Delaware pour les startups qui lèvent des fonds.',

    // Service 3 — LLM SEO
    'srv3-title': 'LLM SEO Optimisation',
    'srv3-tagline': 'Optimisez votre visibilité dans l\'IA générative',
    'srv3-short': 'Stratégie SEO orientée LLM pour apparaître dans ChatGPT, Perplexity, Google AI Overviews et les moteurs de demain.',
    'srv3-desc': "Les moteurs de recherche évoluent vers l'IA. Nous optimisons votre contenu pour qu'il soit cité par les LLMs (ChatGPT, Gemini, Perplexity). Contenu sémantique, schema markup, autorité topique — nous préparons votre visibilité pour le SEO de demain.",
    'srv3-f1': 'Audit SEO technique complet',
    'srv3-f2': 'Stratégie de contenu sémantique & topical authority',
    'srv3-f3': 'Schema.org & structured data avancés',
    'srv3-f4': 'Optimisation pour Google AI Overviews',
    'srv3-f5': 'Citation optimization (ChatGPT, Perplexity, Gemini)',
    'srv3-f6': 'Reporting mensuel & suivi de visibilité IA',
    'srv3-r1': '+3x de citations dans les réponses IA en 90 jours',
    'srv3-r2': 'Apparition dans Google AI Overviews',
    'srv3-r3': 'Trafic organique +40% en 6 mois',
    'srv3-faq-q1': 'En quoi le LLM SEO diffère du SEO classique ?',
    'srv3-faq-a1': 'Le SEO classique cible Google. Le LLM SEO optimise pour que les IAs génératives citent votre contenu dans leurs réponses — une source de trafic en forte croissance.',
    'srv3-faq-q2': 'Combien de temps avant les premiers résultats ?',
    'srv3-faq-a2': 'Les premières citations apparaissent généralement sous 4–8 semaines pour les contenus bien structurés.',

    // Service 4 — Agent Automation
    'srv4-title': 'Agent Automation Process',
    'srv4-tagline': 'Remplacez les tâches répétitives par des agents IA autonomes',
    'srv4-short': 'Automatisation des processus métier, agents IA autonomes et remplacement de tâches manuelles répétitives.',
    'srv4-desc': "Nous construisons des agents IA qui travaillent 24h/24 à votre place : traitement de leads, réponses emails, gestion de données, reporting automatique. Chaque heure économisée est directement réinjectée dans votre croissance.",
    'srv4-f1': 'Audit des processus manuels & identification ROI',
    'srv4-f2': 'Agents IA autonomes (Make, n8n, LangChain)',
    'srv4-f3': 'Automatisation CRM & pipeline commercial',
    'srv4-f4': 'Traitement automatique emails / documents',
    'srv4-f5': 'Intégrations API (Slack, Notion, HubSpot…)',
    'srv4-f6': 'Dashboard de monitoring des agents',
    'srv4-r1': '-80% de temps sur les tâches répétitives',
    'srv4-r2': 'ROI moyen constaté en 3 mois',
    'srv4-r3': 'Agents actifs 24h/24, 7j/7',
    'srv4-faq-q1': 'Mes équipes doivent‑elles être techniques ?',
    'srv4-faq-a1': 'Non. Nous construisons et maintenons les agents. Vos équipes bénéficient des résultats sans gérer la technique.',
    'srv4-faq-q2': 'Quels outils utilisez‑vous pour les automatisations ?',
    'srv4-faq-a2': 'Make (Integromat), n8n, LangChain, OpenAI API, selon la complexité du besoin.',
    'hero-badge': 'Agence Mieux Notée 2025',
    'hero-cta1': 'Auditer mon Business',
    'hero-cta2': 'Nos Réalisations',
    'hero-float-1-title': 'Croissance +120%',
    'hero-float-1-desc': 'Rapport Analytics',
    'hero-float-2-title': 'Utilisateurs Actifs',
    'hero-subtitle': 'Nous créons les outils sur-mesure qui automatisent votre activité.',
    'hero-subtitle-strong': 'Délais garantis. Budget respecté. Zéro jargon technique.',
    'partners-title': 'Ils nous font confiance',
    'work-title': 'Projets Sélectionnés',
    'work-subtitle': "Nous ne faisons pas que du design; nous construisons des écosystèmes digitaux qui scalent.",
    'work-link': 'Voir tous les projets',
    'bento-label': 'Notre Expertise',
    'bento-title': "Tout ce qu'il faut pour Automatiser",
    'bento-subtitle': "De l'analyse de vos processus jusqu'au déploiement final, nous couvrons tous les aspects techniques et créatifs.",
    'bento-1-title': 'Interfaces & Ergonomie',
    'bento-1-desc': "Nous concevons des outils internes intuitifs que vos équipes prendront plaisir à utiliser au quotidien. Fini les logiciels complexes.",
    'bento-2-title': 'Développement Sur-Mesure',
    'bento-2-desc': 'Des systèmes robustes pour digitaliser votre métier.',
    'bento-3-title': 'Automatisation',
    'bento-3-desc': 'Connexions API & CRM.',
    'bento-4-title': 'Accessibilité',
    'bento-4-desc': 'Vos outils sur mobile & tablette.',
    'steps-label': 'Notre Processus',
    'steps-title': "De l'Audit à l'Action",
    'step-1-title': 'Audit & Compréhension',
    'step-1-desc': "Nous commençons par comprendre votre métier. Nous analysons vos goulots d'étranglement et vos pertes de temps pour définir où l'automatisation aura le plus d'impact ROI.",
    'step-2-title': 'Construction Agile',
    'step-2-desc': "Pas d'effet tunnel. Nous développons vos outils étape par étape. Vous validez chaque fonctionnalité toutes les deux semaines. Vous gardez le contrôle total sur le budget et la direction.",
    'step-3-title': 'Déploiement & Formation',
    'step-3-desc': "La technique n'est rien sans adoption. Nous installons les outils et formons vos équipes pour qu'elles gagnent du temps dès le premier jour. Zéro rupture d'activité.",
    'testim-title': 'Ils nous font confiance',
    'testim-subtitle': "Des résultats concrets, pas de promesses en l'air.",
    'testim-1': '"On perdait 2 jours par semaine sur Excel. Diez a créé un outil sur-mesure qui a tout automatisé. L\'investissement a été rentabilisé en 3 mois."',
    'testim-2': '"J\'avais peur que ce soit trop technique pour nous. L\'équipe a été ultra-pédagogue et l\'outil est hyper simple à utiliser. Je recommande."',
    'testim-3': '"Enfin une agence qui respecte les délais ! Outil livré à la date prévue, budget respecté à l\'euro près. Ça change tout."',
    'pricing-title': 'Prix Simples, Grande Valeur',
    'pricing-subtitle': "Choisissez le plan adapté à votre stade. Pas de frais cachés, juste des résultats.",
    'price-1-title': 'Démarrage',
    'price-1-period': '/mois',
    'price-1-desc': 'Parfait pour les MVPs et la validation rapide.',
    'price-1-f1': 'Système de Design',
    'price-1-f2': '5 Pages Frontend',
    'price-1-f3': 'SEO de base',
    'price-1-f4': 'Support Backend',
    'price-1-btn': 'Commencer',
    'price-2-badge': 'Populaire',
    'price-2-title': 'Croissance',
    'price-2-period': '/mois',
    'price-2-desc': 'Pour les équipes en croissance nécessitant un partenaire produit.',
    'price-2-f1': 'Suite UI/UX Complète',
    'price-2-f2': 'App React/Next.js',
    'price-2-f3': 'Intégration API',
    'price-2-f4': 'Sprints Hebdomadaires',
    'price-2-btn': 'Choisir Pro',
    'price-3-title': 'Entreprise',
    'price-3-period': '/devis',
    'price-3-desc': 'Transformation digitale complète pour organisations établies.',
    'price-3-f1': 'Équipe Dédiée (5+)',
    'price-3-f2': 'Support 24/7',
    'price-3-f3': 'Architecture Cloud',
    'price-3-f4': 'Sécurité Avancée',
    'price-3-btn': 'Contacter Ventes',
    'faq-title': 'Questions Fréquentes',
    'faq-q1': 'Combien de temps dure un projet typique ?',
    'faq-a1': 'Les délais varient selon la complexité. Une landing page peut prendre 2 semaines, un SaaS complet 8-12 semaines. Nous travaillons en sprints de 2 semaines pour montrer des progrès constants.',
    'faq-q2': 'Assurez-vous le support après lancement ?',
    'faq-a2': 'Absolument. Nous proposons plusieurs forfaits de maintenance pour garder votre produit sécurisé et à jour.',
    'faq-q3': 'Quelles technologies utilisez-vous ?',
    'faq-a3': 'Nous sommes experts de la stack Javascript moderne : React, Next.js, Node.js et Tailwind CSS pour le frontend et le backend.',
    'manifesto-label': 'Notre Philosophie',
    'manifesto-text': "Nous croyons que la technologie doit servir votre métier, pas le complexifier. Un mauvais logiciel tue la croissance. Un bon outil libère le potentiel de vos équipes. Nous ne vendons pas des lignes de code, nous vendons de la sérénité et de la performance.",
    'cta-title-1': 'Prêt à passer à la',
    'cta-title-2': 'vitesse supérieure ?',
    'cta-subtitle': "Rejoignez les dirigeants qui ont choisi l'efficacité. Transformons vos processus manuels en avantages compétitifs.",
    'cta-btn-1': "Lancer l'Audit Gratuit",
    'cta-btn-2': 'Voir les Cas Clients',
    'footer-desc': 'Nous construisons des produits digitaux qui définissent des catégories et stimulent la croissance.',
    'footer-h-services': 'Services',
    'footer-l-web': 'Développement Web',
    'footer-l-mob': 'Apps Mobiles',
    'footer-l-ui': 'Design UI/UX',
    'footer-l-consult': 'Consulting',
    'footer-h-company': 'Agence',
    'footer-l-about': 'À Propos',
    'footer-l-careers': 'Carrières',
    'footer-l-blog': 'Blog',
    'footer-l-contact': 'Contact',
    'footer-h-newsletter': 'Newsletter',
    'footer-news-text': 'Recevez les dernières tendances.',
    'footer-email-ph': 'Votre email',
    'contact-id': 'contact',
    'work-page-label': 'Portfolio complet',
    'work-page-title': 'Tous nos',
    'work-page-title-accent': 'projets',
    'work-page-subtitle': 'Des écosystèmes digitaux qui scalent. Chaque projet est conçu pour durer et performer.',
    'work-filter-all': 'Tous',
    'work-empty': 'Aucun projet pour ce filtre.',
    'work-cta-title': 'Votre projet,',
    'work-cta-accent': 'notre prochain succès',
    'work-cta-sub': 'Audit gratuit · Délais garantis · Budget respecté',
    'work-cta-btn': 'Démarrer mon projet',
    'work-back': 'Retour',
    'blog-label': 'Nos Articles',
    'blog-title': 'Le Blog',
    'blog-title-accent': 'Diez',
    'blog-subtitle': 'Conseils pratiques sur la transformation digitale, l\'automatisation et le développement.',
    'blog-read': 'Lire l\'article',
    'blog-back': 'Retour',
    'blog-empty': 'Aucun article pour le moment.',
    'blog-share': 'Partager',

    // ── Page Contact / Onboarding ──
    'contact-page-title': 'Démarrez votre projet',
    'contact-page-subtitle': 'Parlez-nous de vos besoins — ça prend 2 minutes chrono.',
    'contact-step': 'Étape',
    'contact-of': 'sur',
    'contact-next': 'Suivant',
    'contact-prev': 'Précédent',
    'contact-send': 'Envoyer ma demande',
    'contact-sending': 'Envoi en cours…',
    'contact-success-title': 'Demande reçue ! 🎉',
    'contact-success-sub': 'Nous vous répondons sous 24h.',
    'contact-success-btn': 'Retour à l\'accueil',
    // Step 1
    'contact-s1-title': 'Ravi de vous rencontrer !',
    'contact-s1-subtitle': 'Quel est votre prénom ?',
    'contact-s1-placeholder': 'Votre prénom',
    // Step 2
    'contact-s2-title': 'De quoi avez-vous besoin ?',
    'contact-s2-subtitle': 'Choisissez l\'option qui correspond le mieux à votre projet.',
    'contact-s2-opt1': '⚡ Automatisation de processus',
    'contact-s2-opt1-desc': 'Éliminer les tâches répétitives',
    'contact-s2-opt2': '🛠️ Outil interne sur-mesure',
    'contact-s2-opt2-desc': 'Dashboard, CRM, suivi…',
    'contact-s2-opt3': '🌐 Site web / Application',
    'contact-s2-opt3-desc': 'Landing page, SaaS, portail',
    'contact-s2-opt4': '📊 Analytics & Reporting',
    'contact-s2-opt4-desc': 'Dashboards & KPIs personnalisés',
    'contact-s2-opt5': '🔗 API / Intégrations',
    'contact-s2-opt5-desc': 'Connecter vos outils entre eux',
    'contact-s2-opt6': '💡 Autre / Pas encore sûr',
    'contact-s2-opt6-desc': 'On définit ça ensemble',
    // Step 3
    'contact-s3-title': 'Dites-nous en plus',
    'contact-s3-subtitle': 'Décrivez brièvement votre projet ou le problème à résoudre.',
    'contact-s3-placeholder': 'Ex : Nous perdons 3h par jour à saisir manuellement des factures. Nous avons besoin d\'un système automatisé…',
    // Step 4
    'contact-s4-title': 'Quel est votre budget ?',
    'contact-s4-subtitle': 'Cela nous aide à vous proposer la bonne solution dès le départ.',
    'contact-s4-opt1': '< 2 000 €',
    'contact-s4-opt1-desc': 'Solution rapide et ciblée',
    'contact-s4-opt2': '2 000 – 5 000 €',
    'contact-s4-opt2-desc': 'Projet standard',
    'contact-s4-opt3': '5 000 – 15 000 €',
    'contact-s4-opt3-desc': 'Projet avancé',
    'contact-s4-opt4': '> 15 000 €',
    'contact-s4-opt4-desc': 'Transformation complète',
    'contact-s4-opt5': 'Je souhaite d\'abord un devis',
    'contact-s4-opt5-desc': 'Estimation gratuite',
    // Step 5
    'contact-s5-title': 'Quand souhaitez-vous démarrer ?',
    'contact-s5-subtitle': 'Pour planifier les bonnes disponibilités.',
    'contact-s5-opt1': '🔥 Dès que possible',
    'contact-s5-opt2': '📅 Dans le mois',
    'contact-s5-opt3': '🗓️ Dans 2–3 mois',
    'contact-s5-opt4': '🔭 Je suis juste en exploration',
    // Step 6
    'contact-s6-title': 'Presque terminé !',
    'contact-s6-subtitle': 'Où vous envoyer notre proposition ?',
    'contact-s6-email': 'Email *',
    'contact-s6-email-ph': 'vous@email.com',
    'contact-s6-phone': 'Téléphone (optionnel)',
    'contact-s6-phone-ph': '+33 6 00 00 00 00',
    'contact-s6-privacy': 'Vos informations sont strictement confidentielles et jamais partagées.',

    // ── Page Recrutement ──
    'recruit-page-title': 'Rejoignez l\'équipe',
    'recruit-page-subtitle': 'Envoyez-nous votre candidature — ça prend 2 minutes.',
    'recruit-step': 'Étape',
    'recruit-next': 'Suivant',
    'recruit-prev': 'Précédent',
    'recruit-send': 'Envoyer ma candidature',
    'recruit-sending': 'Envoi en cours…',
    'recruit-success-title': 'Candidature envoyée ! 🎉',
    'recruit-success-sub': 'Nous étudions votre profil et vous recontactons rapidement.',
    'recruit-success-btn': 'Retour à l\'accueil',
    // Step 1
    'recruit-s1-title': 'Ravi de vous rencontrer !',
    'recruit-s1-subtitle': 'Comment vous appelez-vous ?',
    'recruit-s1-firstname-ph': 'Prénom',
    'recruit-s1-lastname-ph': 'Nom',
    // Step 2
    'recruit-s2-title': 'Votre CV',
    'recruit-s2-subtitle': 'Déposez votre CV au format PDF (5 Mo max).',
    'recruit-s2-drop': 'Glissez votre PDF ici ou cliquez pour parcourir',
    'recruit-s2-drop-hint': 'PDF uniquement · 5 Mo maximum',
    'recruit-s2-uploading': 'Téléversement en cours…',
    // Step 3
    'recruit-s3-title': 'Votre motivation',
    'recruit-s3-subtitle': 'Présentez-vous brièvement et dites-nous pourquoi Diez Agency vous intéresse.',
    'recruit-s3-placeholder': 'Ex : Développeur full-stack avec 3 ans d\'expérience, passionné par l\'automatisation et les outils sur-mesure…',
    // Step 4
    'recruit-s4-title': 'Presque terminé !',
    'recruit-s4-subtitle': 'Comment vous contacter ?',
    'recruit-s4-email': 'Email *',
    'recruit-s4-email-ph': 'vous@email.com',
    'recruit-s4-phone': 'Téléphone (optionnel)',
    'recruit-s4-phone-ph': '+33 6 00 00 00 00',
    'recruit-s4-privacy': 'Vos informations sont strictement confidentielles et jamais partagées.',
    'footer-l-recruitment': 'Recrutement',
  },
  en: {
    'nav-home': 'Home',
    'nav-services': 'Services',
    'nav-process': 'Process',
    'nav-portfolio': 'Portfolio',
    'nav-blog': 'Blog',
    'nav-testimonials': 'Reviews',
    'nav-contact': 'Contact',

    // ── Services ──
    'services-label': 'What we do',
    'services-title': 'Our Services',
    'services-title-accent': 'Tailored',
    'services-subtitle': "Each service is designed to generate a measurable impact on your growth.",
    'services-cta': 'Start a project',
    'services-link': 'View all services',
    'services-discover': 'Discover this service',
    'services-back': '← Back',
    'services-included': "What's included",
    'services-results': 'Typical results',
    'services-faq': 'Frequently asked questions',
    'services-cta-page-title': 'Ready to start?',
    'services-cta-page-sub': 'Free audit · 24h response · Transparent quote',
    'services-cta-page-btn': "Request a free quote",

    // Service 1 — SaaS / Web / App
    'srv1-title': 'SaaS, Websites & Applications',
    'srv1-tagline': 'Your idea into a complete digital product',
    'srv1-short': 'Design, development and deployment of web platforms, SaaS and custom applications.',
    'srv1-desc': "From wireframe to deployment, we build robust and scalable digital products. Modern interfaces, solid backend, polished user experience — delivered on time.",
    'srv1-f1': 'UI/UX design & Figma prototype',
    'srv1-f2': 'Next.js / React development',
    'srv1-f3': 'Custom backend & API',
    'srv1-f4': 'Database & authentication',
    'srv1-f5': 'Cloud deployment & CI/CD',
    'srv1-f6': 'Technical SEO & performance',
    'srv1-r1': '-60% development time vs traditional agency',
    'srv1-r2': 'MVP delivered in 4–8 weeks',
    'srv1-r3': 'Lighthouse score > 90 guaranteed',
    'srv1-faq-q1': 'How long does a SaaS take on average?',
    'srv1-faq-a1': 'A functional MVP is deliverable in 6–8 weeks. We work in 2-week sprints with continuous validation.',
    'srv1-faq-q2': 'Do you offer post-delivery maintenance?',
    'srv1-faq-a2': 'Yes, with monthly maintenance packages including updates, monitoring and bug fixes.',

    // Service 2 — LLC
    'srv2-title': 'Full LLC Creation',
    'srv2-tagline': 'Launch your US company in 72h',
    'srv2-short': 'Turnkey creation of your American LLC: registration, EIN, bank account and compliance.',
    'srv2-desc': "We handle the entire US incorporation process. LLC registered, EIN obtained, registered agent address, professional bank account opened — without you having to travel.",
    'srv2-f1': 'LLC registration in the optimal state (Wyoming, Delaware…)',
    'srv2-f2': 'EIN (US tax number) obtained',
    'srv2-f3': '12-month Registered Agent included',
    'srv2-f4': 'US online bank account opening',
    'srv2-f5': 'Operating Agreement drafted',
    'srv2-f6': 'Annual compliance & reminders',
    'srv2-r1': 'Operational LLC in less than 72h',
    'srv2-r2': '100% online, no travel required',
    'srv2-r3': 'Access to US Stripe / PayPal payments',
    'srv2-faq-q1': 'Do I need to be a US resident?',
    'srv2-faq-a1': 'No. Any foreign national can create a US LLC without a visa or residency.',
    'srv2-faq-q2': 'Which states do you recommend?',
    'srv2-faq-a2': 'Wyoming for privacy and low fees, Delaware for startups raising funds.',

    // Service 3 — LLM SEO
    'srv3-title': 'LLM SEO Optimization',
    'srv3-tagline': 'Optimize your visibility in generative AI',
    'srv3-short': 'LLM-oriented SEO strategy to appear in ChatGPT, Perplexity, Google AI Overviews and tomorrow\'s engines.',
    'srv3-desc': "Search engines are evolving toward AI. We optimize your content to be cited by LLMs (ChatGPT, Gemini, Perplexity). Semantic content, schema markup, topical authority — we prepare your visibility for the SEO of tomorrow.",
    'srv3-f1': 'Full technical SEO audit',
    'srv3-f2': 'Semantic content strategy & topical authority',
    'srv3-f3': 'Advanced Schema.org & structured data',
    'srv3-f4': 'Google AI Overviews optimization',
    'srv3-f5': 'Citation optimization (ChatGPT, Perplexity, Gemini)',
    'srv3-f6': 'Monthly reporting & AI visibility tracking',
    'srv3-r1': '+3x citations in AI responses within 90 days',
    'srv3-r2': 'Appearance in Google AI Overviews',
    'srv3-r3': '+40% organic traffic in 6 months',
    'srv3-faq-q1': 'How does LLM SEO differ from classic SEO?',
    'srv3-faq-a1': 'Classic SEO targets Google. LLM SEO optimizes for generative AIs to cite your content in their answers — a rapidly growing traffic source.',
    'srv3-faq-q2': 'How long before seeing first results?',
    'srv3-faq-a2': 'First citations typically appear within 4–8 weeks for well-structured content.',

    // Service 4 — Agent Automation
    'srv4-title': 'Agent Automation Process',
    'srv4-tagline': 'Replace repetitive tasks with autonomous AI agents',
    'srv4-short': 'Business process automation, autonomous AI agents and replacement of repetitive manual tasks.',
    'srv4-desc': "We build AI agents that work 24/7 for you: lead processing, email responses, data management, automatic reporting. Every hour saved is directly reinvested in your growth.",
    'srv4-f1': 'Manual process audit & ROI identification',
    'srv4-f2': 'Autonomous AI agents (Make, n8n, LangChain)',
    'srv4-f3': 'CRM & sales pipeline automation',
    'srv4-f4': 'Automatic email / document processing',
    'srv4-f5': 'API integrations (Slack, Notion, HubSpot…)',
    'srv4-f6': 'Agent monitoring dashboard',
    'srv4-r1': '-80% time on repetitive tasks',
    'srv4-r2': 'Average ROI observed in 3 months',
    'srv4-r3': 'Agents active 24/7',
    'srv4-faq-q1': 'Do my teams need to be technical?',
    'srv4-faq-a1': 'No. We build and maintain the agents. Your teams benefit from the results without managing the tech.',
    'srv4-faq-q2': 'What tools do you use for automation?',
    'srv4-faq-a2': 'Make (Integromat), n8n, LangChain, OpenAI API, depending on the complexity of the need.',
    'hero-badge': 'Top Rated Agency 2025',
    'hero-cta1': 'Audit My Business',
    'hero-cta2': 'Our Work',
    'hero-float-1-title': 'Growth +120%',
    'hero-float-1-desc': 'Analytics Report',
    'hero-float-2-title': 'Active Users',
    'hero-subtitle': 'We build custom tools that automate your business.',
    'hero-subtitle-strong': 'Guaranteed deadlines. Respected budget. No technical jargon.',
    'partners-title': 'Trusted by Innovative Companies',
    'work-title': 'Selected Work',
    'work-subtitle': "We don't just design; we build digital ecosystems that scale.",
    'work-link': 'View all projects',
    'bento-label': 'Our Expertise',
    'bento-title': 'Everything you need to Automate',
    'bento-subtitle': 'From process analysis to final deployment, we cover all technical and creative aspects.',
    'bento-1-title': 'Interfaces & Ergonomics',
    'bento-1-desc': 'We design intuitive internal tools that your teams will enjoy using every day. No more complex software.',
    'bento-2-title': 'Custom Development',
    'bento-2-desc': 'Robust systems to digitize your business.',
    'bento-3-title': 'Automation',
    'bento-3-desc': 'API & CRM Connections.',
    'bento-4-title': 'Accessibility',
    'bento-4-desc': 'Your tools on mobile & tablet.',
    'steps-label': 'Our Process',
    'steps-title': 'From Audit to Action',
    'step-1-title': 'Audit & Understanding',
    'step-1-desc': 'We start by understanding your business. We analyze your bottlenecks and time losses to define where automation will have the most ROI impact.',
    'step-2-title': 'Agile Construction',
    'step-2-desc': 'No tunnel effect. We develop your tools step by step. You validate each feature every two weeks. You keep full control over budget and direction.',
    'step-3-title': 'Deployment & Training',
    'step-3-desc': 'Technology is nothing without adoption. We install the tools and train your teams so they save time from day one. Zero business disruption.',
    'testim-title': 'They Trust Us',
    'testim-subtitle': 'Concrete results, no empty promises.',
    'testim-1': '"We were losing 2 days a week on Excel. Diez created a custom tool that automated everything. The investment paid off in 3 months."',
    'testim-2': '"I was afraid it would be too technical for us. The team was super educational and the tool is super simple to use. I recommend."',
    'testim-3': '"Finally an agency that respects deadlines! Tool delivered on the scheduled date, budget respected to the euro. It changes everything."',
    'pricing-title': 'Simple Pricing, Big Value',
    'pricing-subtitle': 'Choose the plan that fits your stage. No hidden fees, just results.',
    'price-1-title': 'Starter',
    'price-1-period': '/mo',
    'price-1-desc': 'Perfect for MVPs and small startups needing quick validation.',
    'price-1-f1': 'Design System',
    'price-1-f2': '5 Pages Frontend',
    'price-1-f3': 'Basic SEO',
    'price-1-f4': 'Backend Support',
    'price-1-btn': 'Get Started',
    'price-2-badge': 'Most Popular',
    'price-2-title': 'Scale Up',
    'price-2-period': '/mo',
    'price-2-desc': 'For growing teams that need a dedicated product partner.',
    'price-2-f1': 'Full UI/UX Suite',
    'price-2-f2': 'React/Next.js App',
    'price-2-f3': 'API Integration',
    'price-2-f4': 'Weekly Sprints',
    'price-2-btn': 'Choose Professional',
    'price-3-title': 'Enterprise',
    'price-3-period': '/quote',
    'price-3-desc': 'Full digital transformation for established organizations.',
    'price-3-f1': 'Dedicated Team (5+)',
    'price-3-f2': '24/7 Support',
    'price-3-f3': 'Cloud Architecture',
    'price-3-f4': 'Advanced Security',
    'price-3-btn': 'Contact Sales',
    'faq-title': 'Frequently Asked Questions',
    'faq-q1': 'How long does a typical project take?',
    'faq-a1': 'Timelines vary depending on complexity. A landing page might take 2 weeks, while a full SaaS MVP usually takes 8-12 weeks. We work in 2-week sprints to show consistent progress.',
    'faq-q2': 'Do you provide post-launch support?',
    'faq-a2': 'Absolutely. We offer various maintenance packages to ensure your product stays secure, updated, and bug-free after launch.',
    'faq-q3': 'What technologies do you use?',
    'faq-a3': 'We specialize in the modern Javascript stack: React, Next.js, Node.js, and Tailwind CSS on the frontend/backend. For mobile, we use React Native.',
    'manifesto-label': 'Our Philosophy',
    'manifesto-text': "We believe technology should serve your business, not complicate it. Bad software kills growth. A good tool unleashes your team's potential. We don't sell lines of code, we sell serenity and performance.",
    'cta-title-1': 'Ready to shift to the',
    'cta-title-2': 'next gear?',
    'cta-subtitle': "Join the leaders who chose efficiency. Let's transform your manual processes into competitive advantages.",
    'cta-btn-1': 'Launch Free Audit',
    'cta-btn-2': 'See Case Studies',
    'footer-desc': 'We build digital products that define categories and drive business growth.',
    'footer-h-services': 'Services',
    'footer-l-web': 'Web Development',
    'footer-l-mob': 'Mobile Apps',
    'footer-l-ui': 'UI/UX Design',
    'footer-l-consult': 'Consulting',
    'footer-h-company': 'Company',
    'footer-l-about': 'About Us',
    'footer-l-careers': 'Careers',
    'footer-l-blog': 'Blog',
    'footer-l-contact': 'Contact',
    'footer-h-newsletter': 'Newsletter',
    'footer-news-text': 'Get the latest trends in your inbox.',
    'footer-email-ph': 'Enter email',
    'contact-id': 'contact',
    'work-page-label': 'Full Portfolio',
    'work-page-title': 'All our',
    'work-page-title-accent': 'projects',
    'work-page-subtitle': 'Digital ecosystems that scale. Every project is built to last and perform.',
    'work-filter-all': 'All',
    'work-empty': 'No projects for this filter.',
    'work-cta-title': 'Your project,',
    'work-cta-accent': 'our next success',
    'work-cta-sub': 'Free audit · Guaranteed deadlines · Respected budget',
    'work-cta-btn': 'Start my project',
    'work-back': 'Back',
    'blog-label': 'Our Articles',
    'blog-title': 'The Diez',
    'blog-title-accent': 'Blog',
    'blog-subtitle': 'Practical advice on digital transformation, automation and development.',
    'blog-read': 'Read article',
    'blog-back': 'Back',
    'blog-empty': 'No articles yet.',
    'blog-share': 'Share',

    // ── Page Contact / Onboarding ──
    'contact-page-title': 'Start your project',
    'contact-page-subtitle': 'Tell us about your needs — it only takes 2 minutes.',
    'contact-step': 'Step',
    'contact-of': 'of',
    'contact-next': 'Next',
    'contact-prev': 'Back',
    'contact-send': 'Send my request',
    'contact-sending': 'Sending…',
    'contact-success-title': 'Request received! 🎉',
    'contact-success-sub': "We'll get back to you within 24 hours.",
    'contact-success-btn': 'Back to home',
    // Step 1
    'contact-s1-title': 'Nice to meet you!',
    'contact-s1-subtitle': 'What is your first name?',
    'contact-s1-placeholder': 'Your first name',
    // Step 2
    'contact-s2-title': 'What do you need?',
    'contact-s2-subtitle': 'Choose the option that best matches your project.',
    'contact-s2-opt1': '⚡ Process Automation',
    'contact-s2-opt1-desc': 'Eliminate repetitive tasks',
    'contact-s2-opt2': '🛠️ Custom Internal Tool',
    'contact-s2-opt2-desc': 'Dashboard, CRM, tracking…',
    'contact-s2-opt3': '🌐 Website / Web App',
    'contact-s2-opt3-desc': 'Landing page, SaaS, portal',
    'contact-s2-opt4': '📊 Analytics & Reporting',
    'contact-s2-opt4-desc': 'Custom dashboards & KPIs',
    'contact-s2-opt5': '🔗 API / Integrations',
    'contact-s2-opt5-desc': 'Connect your tools together',
    'contact-s2-opt6': '💡 Other / Not sure yet',
    'contact-s2-opt6-desc': 'Let\'s define it together',
    // Step 3
    'contact-s3-title': 'Tell us more',
    'contact-s3-subtitle': 'Briefly describe your project or the problem you want to solve.',
    'contact-s3-placeholder': 'Example: We lose 3 hours a day manually entering invoices. We need an automated system…',
    // Step 4
    'contact-s4-title': 'What is your budget?',
    'contact-s4-subtitle': 'This helps us suggest the right solution from the start.',
    'contact-s4-opt1': '< $2,000',
    'contact-s4-opt1-desc': 'Quick & targeted solution',
    'contact-s4-opt2': '$2,000 – $5,000',
    'contact-s4-opt2-desc': 'Standard project',
    'contact-s4-opt3': '$5,000 – $15,000',
    'contact-s4-opt3-desc': 'Advanced project',
    'contact-s4-opt4': '> $15,000',
    'contact-s4-opt4-desc': 'Complete transformation',
    'contact-s4-opt5': 'I\'d like a quote first',
    'contact-s4-opt5-desc': 'Free estimate',
    // Step 5
    'contact-s5-title': 'When do you want to start?',
    'contact-s5-subtitle': 'So we can plan the right availability for you.',
    'contact-s5-opt1': '🔥 As soon as possible',
    'contact-s5-opt2': '📅 Within 1 month',
    'contact-s5-opt3': '🗓️ In 2–3 months',
    'contact-s5-opt4': '🔭 Just exploring for now',
    // Step 6
    'contact-s6-title': 'Almost done!',
    'contact-s6-subtitle': 'Where should we send you our proposal?',
    'contact-s6-email': 'Email *',
    'contact-s6-email-ph': 'your@email.com',
    'contact-s6-phone': 'Phone (optional)',
    'contact-s6-phone-ph': '+1 555 000 0000',
    'contact-s6-privacy': 'Your information is strictly confidential and never shared.',

    // ── Recruitment Page ──
    'recruit-page-title': 'Join the team',
    'recruit-page-subtitle': 'Send us your application — it only takes 2 minutes.',
    'recruit-step': 'Step',
    'recruit-next': 'Next',
    'recruit-prev': 'Back',
    'recruit-send': 'Send my application',
    'recruit-sending': 'Sending…',
    'recruit-success-title': 'Application sent! 🎉',
    'recruit-success-sub': 'We\'ll review your profile and get back to you soon.',
    'recruit-success-btn': 'Back to home',
    // Step 1
    'recruit-s1-title': 'Nice to meet you!',
    'recruit-s1-subtitle': 'What is your name?',
    'recruit-s1-firstname-ph': 'First name',
    'recruit-s1-lastname-ph': 'Last name',
    // Step 2
    'recruit-s2-title': 'Your CV',
    'recruit-s2-subtitle': 'Upload your CV in PDF format (5 MB max).',
    'recruit-s2-drop': 'Drag your PDF here or click to browse',
    'recruit-s2-drop-hint': 'PDF only · 5 MB maximum',
    'recruit-s2-uploading': 'Uploading…',
    // Step 3
    'recruit-s3-title': 'Your motivation',
    'recruit-s3-subtitle': 'Briefly introduce yourself and tell us why you\'re interested in Diez Agency.',
    'recruit-s3-placeholder': 'Example: Full-stack developer with 3 years of experience, passionate about automation and custom tools…',
    // Step 4
    'recruit-s4-title': 'Almost done!',
    'recruit-s4-subtitle': 'How can we reach you?',
    'recruit-s4-email': 'Email *',
    'recruit-s4-email-ph': 'your@email.com',
    'recruit-s4-phone': 'Phone (optional)',
    'recruit-s4-phone-ph': '+1 555 000 0000',
    'recruit-s4-privacy': 'Your information is strictly confidential and never shared.',
    'footer-l-recruitment': 'Recruitment',
  },
};

const LangContext = createContext<LangContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (key: string) => key,
});

export function LangProvider({
  children,
  initialLang = 'fr',
}: {
  children: ReactNode;
  initialLang?: Lang;
}) {
  const [lang, setLangState] = useState<Lang>(initialLang);
  const router = useRouter();
  const pathname = usePathname();

  const setLang = (newLang: Lang) => {
    // Sauvegarde cookie 1 an
    document.cookie = `lang=${newLang};path=/;max-age=31536000;SameSite=Lax`;
    setLangState(newLang);
    // Redirect vers la même page dans l'autre langue
    const newPath = pathname.replace(/^\/(fr|en)/, `/${newLang}`);
    router.push(newPath);
  };

  const t = (key: string) => translations[lang][key] ?? key;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
