'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useRouter, usePathname } from 'next/navigation';

export type Lang = 'fr' | 'en';

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    'nav-home': 'Accueil',
    'nav-services': 'Expertise',
    'nav-process': 'Process',
    'nav-portfolio': 'Réalisations',
    'nav-blog': 'Blog',
    'nav-testimonials': 'Avis',
    'nav-contact': 'Contact',
    'hero-badge': 'Agence Mieux Notée 2025',
    'hero-cta1': 'Auditer mon Business',
    'hero-cta2': 'Nos Réalisations',
    'hero-float-1-title': 'Croissance +120%',
    'hero-float-1-desc': 'Rapport Analytics',
    'hero-float-2-title': 'Utilisateurs Actifs',
    'hero-subtitle': 'Nous créons les outils sur-mesure qui automatisent votre activité.',
    'hero-subtitle-strong': 'Délais garantis. Budget respecté. Zéro jargon technique.',
    'partners-title': 'Ils nous font confiance',
    'work-title': 'Projets Sélectionnés',
    'work-subtitle': "Nous ne faisons pas que du design; nous construisons des écosystèmes digitaux qui scalent.",
    'work-link': 'Voir tous les projets',
    'bento-label': 'Notre Expertise',
    'bento-title': "Tout ce qu'il faut pour Automatiser",
    'bento-subtitle': "De l'analyse de vos processus jusqu'au déploiement final, nous couvrons tous les aspects techniques et créatifs.",
    'bento-1-title': 'Interfaces & Ergonomie',
    'bento-1-desc': "Nous concevons des outils internes intuitifs que vos équipes prendront plaisir à utiliser au quotidien. Fini les logiciels complexes.",
    'bento-2-title': 'Développement Sur-Mesure',
    'bento-2-desc': 'Des systèmes robustes pour digitaliser votre métier.',
    'bento-3-title': 'Automatisation',
    'bento-3-desc': 'Connexions API & CRM.',
    'bento-4-title': 'Accessibilité',
    'bento-4-desc': 'Vos outils sur mobile & tablette.',
    'steps-label': 'Notre Processus',
    'steps-title': "De l'Audit à l'Action",
    'step-1-title': 'Audit & Compréhension',
    'step-1-desc': "Nous commençons par comprendre votre métier. Nous analysons vos goulots d'étranglement et vos pertes de temps pour définir où l'automatisation aura le plus d'impact ROI.",
    'step-2-title': 'Construction Agile',
    'step-2-desc': "Pas d'effet tunnel. Nous développons vos outils étape par étape. Vous validez chaque fonctionnalité toutes les deux semaines. Vous gardez le contrôle total sur le budget et la direction.",
    'step-3-title': 'Déploiement & Formation',
    'step-3-desc': "La technique n'est rien sans adoption. Nous installons les outils et formons vos équipes pour qu'elles gagnent du temps dès le premier jour. Zéro rupture d'activité.",
    'testim-title': 'Ils nous font confiance',
    'testim-subtitle': "Des résultats concrets, pas de promesses en l'air.",
    'testim-1': '"On perdait 2 jours par semaine sur Excel. Diez a créé un outil sur-mesure qui a tout automatisé. L\'investissement a été rentabilisé en 3 mois."',
    'testim-2': '"J\'avais peur que ce soit trop technique pour nous. L\'équipe a été ultra-pédagogue et l\'outil est hyper simple à utiliser. Je recommande."',
    'testim-3': '"Enfin une agence qui respecte les délais ! Outil livré à la date prévue, budget respecté à l\'euro près. Ça change tout."',
    'pricing-title': 'Prix Simples, Grande Valeur',
    'pricing-subtitle': "Choisissez le plan adapté à votre stade. Pas de frais cachés, juste des résultats.",
    'price-1-title': 'Démarrage',
    'price-1-period': '/mois',
    'price-1-desc': 'Parfait pour les MVPs et la validation rapide.',
    'price-1-f1': 'Système de Design',
    'price-1-f2': '5 Pages Frontend',
    'price-1-f3': 'SEO de base',
    'price-1-f4': 'Support Backend',
    'price-1-btn': 'Commencer',
    'price-2-badge': 'Populaire',
    'price-2-title': 'Croissance',
    'price-2-period': '/mois',
    'price-2-desc': 'Pour les équipes en croissance nécessitant un partenaire produit.',
    'price-2-f1': 'Suite UI/UX Complète',
    'price-2-f2': 'App React/Next.js',
    'price-2-f3': 'Intégration API',
    'price-2-f4': 'Sprints Hebdomadaires',
    'price-2-btn': 'Choisir Pro',
    'price-3-title': 'Entreprise',
    'price-3-period': '/devis',
    'price-3-desc': 'Transformation digitale complète pour organisations établies.',
    'price-3-f1': 'Équipe Dédiée (5+)',
    'price-3-f2': 'Support 24/7',
    'price-3-f3': 'Architecture Cloud',
    'price-3-f4': 'Sécurité Avancée',
    'price-3-btn': 'Contacter Ventes',
    'faq-title': 'Questions Fréquentes',
    'faq-q1': 'Combien de temps dure un projet typique ?',
    'faq-a1': 'Les délais varient selon la complexité. Une landing page peut prendre 2 semaines, un SaaS complet 8-12 semaines. Nous travaillons en sprints de 2 semaines pour montrer des progrès constants.',
    'faq-q2': 'Assurez-vous le support après lancement ?',
    'faq-a2': 'Absolument. Nous proposons plusieurs forfaits de maintenance pour garder votre produit sécurisé et à jour.',
    'faq-q3': 'Quelles technologies utilisez-vous ?',
    'faq-a3': 'Nous sommes experts de la stack Javascript moderne : React, Next.js, Node.js et Tailwind CSS pour le frontend et le backend.',
    'manifesto-label': 'Notre Philosophie',
    'manifesto-text': "Nous croyons que la technologie doit servir votre métier, pas le complexifier. Un mauvais logiciel tue la croissance. Un bon outil libère le potentiel de vos équipes. Nous ne vendons pas des lignes de code, nous vendons de la sérénité et de la performance.",
    'cta-title-1': 'Prêt à passer à la',
    'cta-title-2': 'vitesse supérieure ?',
    'cta-subtitle': "Rejoignez les dirigeants qui ont choisi l'efficacité. Transformons vos processus manuels en avantages compétitifs.",
    'cta-btn-1': "Lancer l'Audit Gratuit",
    'cta-btn-2': 'Voir les Cas Clients',
    'footer-desc': 'Nous construisons des produits digitaux qui définissent des catégories et stimulent la croissance.',
    'footer-h-services': 'Services',
    'footer-l-web': 'Développement Web',
    'footer-l-mob': 'Apps Mobiles',
    'footer-l-ui': 'Design UI/UX',
    'footer-l-consult': 'Consulting',
    'footer-h-company': 'Agence',
    'footer-l-about': 'À Propos',
    'footer-l-careers': 'Carrières',
    'footer-l-blog': 'Blog',
    'footer-l-contact': 'Contact',
    'footer-h-newsletter': 'Newsletter',
    'footer-news-text': 'Recevez les dernières tendances.',
    'footer-email-ph': 'Votre email',
    'contact-id': 'contact',
    'work-page-label': 'Portfolio complet',
    'work-page-title': 'Tous nos',
    'work-page-title-accent': 'projets',
    'work-page-subtitle': 'Des écosystèmes digitaux qui scalent. Chaque projet est conçu pour durer et performer.',
    'work-filter-all': 'Tous',
    'work-empty': 'Aucun projet pour ce filtre.',
    'work-cta-title': 'Votre projet,',
    'work-cta-accent': 'notre prochain succès',
    'work-cta-sub': 'Audit gratuit · Délais garantis · Budget respecté',
    'work-cta-btn': 'Démarrer mon projet',
    'work-back': 'Retour',
    'blog-label': 'Nos Articles',
    'blog-title': 'Le Blog',
    'blog-title-accent': 'Diez',
    'blog-subtitle': 'Conseils pratiques sur la transformation digitale, l\'automatisation et le développement.',
    'blog-read': 'Lire l\'article',
    'blog-back': 'Retour',
    'blog-empty': 'Aucun article pour le moment.',
    'blog-share': 'Partager',

    // ── Page Contact / Onboarding ──
    'contact-page-title': 'Démarrez votre projet',
    'contact-page-subtitle': 'Parlez-nous de vos besoins — ça prend 2 minutes chrono.',
    'contact-step': 'Étape',
    'contact-of': 'sur',
    'contact-next': 'Suivant',
    'contact-prev': 'Précédent',
    'contact-send': 'Envoyer ma demande',
    'contact-sending': 'Envoi en cours…',
    'contact-success-title': 'Demande reçue ! 🎉',
    'contact-success-sub': 'Nous vous répondons sous 24h.',
    'contact-success-btn': 'Retour à l\'accueil',
    // Step 1
    'contact-s1-title': 'Ravi de vous rencontrer !',
    'contact-s1-subtitle': 'Quel est votre prénom ?',
    'contact-s1-placeholder': 'Votre prénom',
    // Step 2
    'contact-s2-title': 'De quoi avez-vous besoin ?',
    'contact-s2-subtitle': 'Choisissez l\'option qui correspond le mieux à votre projet.',
    'contact-s2-opt1': '⚡ Automatisation de processus',
    'contact-s2-opt1-desc': 'Éliminer les tâches répétitives',
    'contact-s2-opt2': '🛠️ Outil interne sur-mesure',
    'contact-s2-opt2-desc': 'Dashboard, CRM, suivi…',
    'contact-s2-opt3': '🌐 Site web / Application',
    'contact-s2-opt3-desc': 'Landing page, SaaS, portail',
    'contact-s2-opt4': '📊 Analytics & Reporting',
    'contact-s2-opt4-desc': 'Dashboards & KPIs personnalisés',
    'contact-s2-opt5': '🔗 API / Intégrations',
    'contact-s2-opt5-desc': 'Connecter vos outils entre eux',
    'contact-s2-opt6': '💡 Autre / Pas encore sûr',
    'contact-s2-opt6-desc': 'On définit ça ensemble',
    // Step 3
    'contact-s3-title': 'Dites-nous en plus',
    'contact-s3-subtitle': 'Décrivez brièvement votre projet ou le problème à résoudre.',
    'contact-s3-placeholder': 'Ex : Nous perdons 3h par jour à saisir manuellement des factures. Nous avons besoin d\'un système automatisé…',
    // Step 4
    'contact-s4-title': 'Quel est votre budget ?',
    'contact-s4-subtitle': 'Cela nous aide à vous proposer la bonne solution dès le départ.',
    'contact-s4-opt1': '< 2 000 €',
    'contact-s4-opt1-desc': 'Solution rapide et ciblée',
    'contact-s4-opt2': '2 000 – 5 000 €',
    'contact-s4-opt2-desc': 'Projet standard',
    'contact-s4-opt3': '5 000 – 15 000 €',
    'contact-s4-opt3-desc': 'Projet avancé',
    'contact-s4-opt4': '> 15 000 €',
    'contact-s4-opt4-desc': 'Transformation complète',
    'contact-s4-opt5': 'Je souhaite d\'abord un devis',
    'contact-s4-opt5-desc': 'Estimation gratuite',
    // Step 5
    'contact-s5-title': 'Quand souhaitez-vous démarrer ?',
    'contact-s5-subtitle': 'Pour planifier les bonnes disponibilités.',
    'contact-s5-opt1': '🔥 Dès que possible',
    'contact-s5-opt2': '📅 Dans le mois',
    'contact-s5-opt3': '🗓️ Dans 2–3 mois',
    'contact-s5-opt4': '🔭 Je suis juste en exploration',
    // Step 6
    'contact-s6-title': 'Presque terminé !',
    'contact-s6-subtitle': 'Où vous envoyer notre proposition ?',
    'contact-s6-email': 'Email *',
    'contact-s6-email-ph': 'vous@email.com',
    'contact-s6-phone': 'Téléphone (optionnel)',
    'contact-s6-phone-ph': '+33 6 00 00 00 00',
    'contact-s6-privacy': 'Vos informations sont strictement confidentielles et jamais partagées.',
  },
  en: {
    'nav-home': 'Home',
    'nav-services': 'Expertise',
    'nav-process': 'Process',
    'nav-portfolio': 'Portfolio',
    'nav-blog': 'Blog',
    'nav-testimonials': 'Reviews',
    'nav-contact': 'Contact',
    'hero-badge': 'Top Rated Agency 2025',
    'hero-cta1': 'Audit My Business',
    'hero-cta2': 'Our Work',
    'hero-float-1-title': 'Growth +120%',
    'hero-float-1-desc': 'Analytics Report',
    'hero-float-2-title': 'Active Users',
    'hero-subtitle': 'We build custom tools that automate your business.',
    'hero-subtitle-strong': 'Guaranteed deadlines. Respected budget. No technical jargon.',
    'partners-title': 'Trusted by Innovative Companies',
    'work-title': 'Selected Work',
    'work-subtitle': "We don't just design; we build digital ecosystems that scale.",
    'work-link': 'View all projects',
    'bento-label': 'Our Expertise',
    'bento-title': 'Everything you need to Automate',
    'bento-subtitle': 'From process analysis to final deployment, we cover all technical and creative aspects.',
    'bento-1-title': 'Interfaces & Ergonomics',
    'bento-1-desc': 'We design intuitive internal tools that your teams will enjoy using every day. No more complex software.',
    'bento-2-title': 'Custom Development',
    'bento-2-desc': 'Robust systems to digitize your business.',
    'bento-3-title': 'Automation',
    'bento-3-desc': 'API & CRM Connections.',
    'bento-4-title': 'Accessibility',
    'bento-4-desc': 'Your tools on mobile & tablet.',
    'steps-label': 'Our Process',
    'steps-title': 'From Audit to Action',
    'step-1-title': 'Audit & Understanding',
    'step-1-desc': 'We start by understanding your business. We analyze your bottlenecks and time losses to define where automation will have the most ROI impact.',
    'step-2-title': 'Agile Construction',
    'step-2-desc': 'No tunnel effect. We develop your tools step by step. You validate each feature every two weeks. You keep full control over budget and direction.',
    'step-3-title': 'Deployment & Training',
    'step-3-desc': 'Technology is nothing without adoption. We install the tools and train your teams so they save time from day one. Zero business disruption.',
    'testim-title': 'They Trust Us',
    'testim-subtitle': 'Concrete results, no empty promises.',
    'testim-1': '"We were losing 2 days a week on Excel. Diez created a custom tool that automated everything. The investment paid off in 3 months."',
    'testim-2': '"I was afraid it would be too technical for us. The team was super educational and the tool is super simple to use. I recommend."',
    'testim-3': '"Finally an agency that respects deadlines! Tool delivered on the scheduled date, budget respected to the euro. It changes everything."',
    'pricing-title': 'Simple Pricing, Big Value',
    'pricing-subtitle': 'Choose the plan that fits your stage. No hidden fees, just results.',
    'price-1-title': 'Starter',
    'price-1-period': '/mo',
    'price-1-desc': 'Perfect for MVPs and small startups needing quick validation.',
    'price-1-f1': 'Design System',
    'price-1-f2': '5 Pages Frontend',
    'price-1-f3': 'Basic SEO',
    'price-1-f4': 'Backend Support',
    'price-1-btn': 'Get Started',
    'price-2-badge': 'Most Popular',
    'price-2-title': 'Scale Up',
    'price-2-period': '/mo',
    'price-2-desc': 'For growing teams that need a dedicated product partner.',
    'price-2-f1': 'Full UI/UX Suite',
    'price-2-f2': 'React/Next.js App',
    'price-2-f3': 'API Integration',
    'price-2-f4': 'Weekly Sprints',
    'price-2-btn': 'Choose Professional',
    'price-3-title': 'Enterprise',
    'price-3-period': '/quote',
    'price-3-desc': 'Full digital transformation for established organizations.',
    'price-3-f1': 'Dedicated Team (5+)',
    'price-3-f2': '24/7 Support',
    'price-3-f3': 'Cloud Architecture',
    'price-3-f4': 'Advanced Security',
    'price-3-btn': 'Contact Sales',
    'faq-title': 'Frequently Asked Questions',
    'faq-q1': 'How long does a typical project take?',
    'faq-a1': 'Timelines vary depending on complexity. A landing page might take 2 weeks, while a full SaaS MVP usually takes 8-12 weeks. We work in 2-week sprints to show consistent progress.',
    'faq-q2': 'Do you provide post-launch support?',
    'faq-a2': 'Absolutely. We offer various maintenance packages to ensure your product stays secure, updated, and bug-free after launch.',
    'faq-q3': 'What technologies do you use?',
    'faq-a3': 'We specialize in the modern Javascript stack: React, Next.js, Node.js, and Tailwind CSS on the frontend/backend. For mobile, we use React Native.',
    'manifesto-label': 'Our Philosophy',
    'manifesto-text': "We believe technology should serve your business, not complicate it. Bad software kills growth. A good tool unleashes your team's potential. We don't sell lines of code, we sell serenity and performance.",
    'cta-title-1': 'Ready to shift to the',
    'cta-title-2': 'next gear?',
    'cta-subtitle': "Join the leaders who chose efficiency. Let's transform your manual processes into competitive advantages.",
    'cta-btn-1': 'Launch Free Audit',
    'cta-btn-2': 'See Case Studies',
    'footer-desc': 'We build digital products that define categories and drive business growth.',
    'footer-h-services': 'Services',
    'footer-l-web': 'Web Development',
    'footer-l-mob': 'Mobile Apps',
    'footer-l-ui': 'UI/UX Design',
    'footer-l-consult': 'Consulting',
    'footer-h-company': 'Company',
    'footer-l-about': 'About Us',
    'footer-l-careers': 'Careers',
    'footer-l-blog': 'Blog',
    'footer-l-contact': 'Contact',
    'footer-h-newsletter': 'Newsletter',
    'footer-news-text': 'Get the latest trends in your inbox.',
    'footer-email-ph': 'Enter email',
    'contact-id': 'contact',
    'work-page-label': 'Full Portfolio',
    'work-page-title': 'All our',
    'work-page-title-accent': 'projects',
    'work-page-subtitle': 'Digital ecosystems that scale. Every project is built to last and perform.',
    'work-filter-all': 'All',
    'work-empty': 'No projects for this filter.',
    'work-cta-title': 'Your project,',
    'work-cta-accent': 'our next success',
    'work-cta-sub': 'Free audit · Guaranteed deadlines · Respected budget',
    'work-cta-btn': 'Start my project',
    'work-back': 'Back',
    'blog-label': 'Our Articles',
    'blog-title': 'The Diez',
    'blog-title-accent': 'Blog',
    'blog-subtitle': 'Practical advice on digital transformation, automation and development.',
    'blog-read': 'Read article',
    'blog-back': 'Back',
    'blog-empty': 'No articles yet.',
    'blog-share': 'Share',

    // ── Page Contact / Onboarding ──
    'contact-page-title': 'Start your project',
    'contact-page-subtitle': 'Tell us about your needs — it only takes 2 minutes.',
    'contact-step': 'Step',
    'contact-of': 'of',
    'contact-next': 'Next',
    'contact-prev': 'Back',
    'contact-send': 'Send my request',
    'contact-sending': 'Sending…',
    'contact-success-title': 'Request received! 🎉',
    'contact-success-sub': "We'll get back to you within 24 hours.",
    'contact-success-btn': 'Back to home',
    // Step 1
    'contact-s1-title': 'Nice to meet you!',
    'contact-s1-subtitle': 'What is your first name?',
    'contact-s1-placeholder': 'Your first name',
    // Step 2
    'contact-s2-title': 'What do you need?',
    'contact-s2-subtitle': 'Choose the option that best matches your project.',
    'contact-s2-opt1': '⚡ Process Automation',
    'contact-s2-opt1-desc': 'Eliminate repetitive tasks',
    'contact-s2-opt2': '🛠️ Custom Internal Tool',
    'contact-s2-opt2-desc': 'Dashboard, CRM, tracking…',
    'contact-s2-opt3': '🌐 Website / Web App',
    'contact-s2-opt3-desc': 'Landing page, SaaS, portal',
    'contact-s2-opt4': '📊 Analytics & Reporting',
    'contact-s2-opt4-desc': 'Custom dashboards & KPIs',
    'contact-s2-opt5': '🔗 API / Integrations',
    'contact-s2-opt5-desc': 'Connect your tools together',
    'contact-s2-opt6': '💡 Other / Not sure yet',
    'contact-s2-opt6-desc': 'Let\'s define it together',
    // Step 3
    'contact-s3-title': 'Tell us more',
    'contact-s3-subtitle': 'Briefly describe your project or the problem you want to solve.',
    'contact-s3-placeholder': 'Example: We lose 3 hours a day manually entering invoices. We need an automated system…',
    // Step 4
    'contact-s4-title': 'What is your budget?',
    'contact-s4-subtitle': 'This helps us suggest the right solution from the start.',
    'contact-s4-opt1': '< $2,000',
    'contact-s4-opt1-desc': 'Quick & targeted solution',
    'contact-s4-opt2': '$2,000 – $5,000',
    'contact-s4-opt2-desc': 'Standard project',
    'contact-s4-opt3': '$5,000 – $15,000',
    'contact-s4-opt3-desc': 'Advanced project',
    'contact-s4-opt4': '> $15,000',
    'contact-s4-opt4-desc': 'Complete transformation',
    'contact-s4-opt5': 'I\'d like a quote first',
    'contact-s4-opt5-desc': 'Free estimate',
    // Step 5
    'contact-s5-title': 'When do you want to start?',
    'contact-s5-subtitle': 'So we can plan the right availability for you.',
    'contact-s5-opt1': '🔥 As soon as possible',
    'contact-s5-opt2': '📅 Within 1 month',
    'contact-s5-opt3': '🗓️ In 2–3 months',
    'contact-s5-opt4': '🔭 Just exploring for now',
    // Step 6
    'contact-s6-title': 'Almost done!',
    'contact-s6-subtitle': 'Where should we send you our proposal?',
    'contact-s6-email': 'Email *',
    'contact-s6-email-ph': 'your@email.com',
    'contact-s6-phone': 'Phone (optional)',
    'contact-s6-phone-ph': '+1 555 000 0000',
    'contact-s6-privacy': 'Your information is strictly confidential and never shared.',
  },
};

const LangContext = createContext<LangContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (key: string) => key,
});

export function LangProvider({
  children,
  initialLang = 'fr',
}: {
  children: ReactNode;
  initialLang?: Lang;
}) {
  const [lang, setLangState] = useState<Lang>(initialLang);
  const router = useRouter();
  const pathname = usePathname();

  const setLang = (newLang: Lang) => {
    // Sauvegarde cookie 1 an
    document.cookie = `lang=${newLang};path=/;max-age=31536000;SameSite=Lax`;
    setLangState(newLang);
    // Redirect vers la même page dans l'autre langue
    const newPath = pathname.replace(/^\/(fr|en)/, `/${newLang}`);
    router.push(newPath);
  };

  const t = (key: string) => translations[lang][key] ?? key;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
